/*
 * This file was autogenerated by TinyMPC on Fri May 24 14:41:40 2024
 */

#pragma once

#include "types.hpp"

#ifdef __cplusplus
extern "C" {
#endif

extern TinySolver tiny_solver;

#ifdef __cplusplus
}
#endif
